### ISSUE TITLE
No Joystick support with Flatpak version

### ISSUE THREAD

**Issue by xalmat** [flathub/net.supertuxkart.SuperTuxKart#2]
I'm trying to play SuperTuxKart on Kubuntu 18.04 using the Flatpak version. However, it does not detect my Joysticks properly (Specifically Xbox 360, Xbox One, and 8bitdo NES30 Pro). However, if I use the normal install from the Kubuntu repos, the joysticks work just fine.

**Comment by xalmat** [comment]
Update:
Running the command "flatpak run --device=all net.supertuxkart.SuperTuxKart" DOES allow my joystick to work.

**Comment by cosmo-ray** [comment]
last commit should fix this.
I've made the patch in a hurry, sorry I forgot to close this issue in my Poll Request. (by using the #close GitHub Markdown stuff)
