### ISSUE TITLE
Compile the latest version of SuperTuxKart

### ISSUE THREAD

**Issue by ADBeveridge** [flathub/net.supertuxkart.SuperTuxKart#33]
Currently this repo is using the last tarball from the Releases page on SuperTuxKart. This version has a bug in battle mode where you can't have any AI. I would suggest using the same commit id as the version on Fedora's DNF repo list for this Flatpak edition, or using the latest commit on the 'main' branch in SuperTuxKart.

**Comment by AsciiWolf** [comment]
Thanks for reporting this! I would prefer to just backport the relevant patch/set of patches into the currently used stable version.

Any chance you could prepare a PR for this?

**Comment by ADBeveridge** [comment]
I'll look into it. I've never used patches though so it might take a while.
